FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y apache2 \
    openssh-server \
    wget
COPY ./html /var/www/html
EXPOSE 80
CMD ["service", "apache2", "start"]